# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-19 04:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0004_auto_20180119_0400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['title']},
        ),
    ]
